# Generated by Django 3.2.1 on 2021-05-05 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='c_time',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 16, 49, 23, 768643)),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_time',
            field=models.DateField(default=models.DateField(default=datetime.datetime(2021, 5, 5, 16, 49, 23, 768643))),
        ),
    ]
