# Generated by Django 3.2.1 on 2021-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210506_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='c_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='m_time',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
